# Generated by Django 6.0.1 on 2026-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racecourse', models.CharField(max_length=100)),
                ('race_time', models.TimeField()),
                ('horse_name', models.CharField(max_length=120)),
                ('odds', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('NAP', 'NAP'), ('NB', 'Next Best'), ('EW', 'Each Way')], default='EW', max_length=10)),
                ('badge', models.CharField(blank=True, help_text='Filename of the racecourse badge (e.g. ascot.png)', max_length=120)),
                ('result', models.CharField(blank=True, choices=[('WON', 'Won'), ('PLACED', 'Placed'), ('LOST', 'Lost'), ('VOID', 'Void / Non‑Runner'), ('', 'Not Settled')], default='', help_text='Outcome of the tip', max_length=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Profit or loss in points (e.g., +2.50 or -1.00)', max_digits=6)),
                ('settled', models.BooleanField(default=False, help_text='Tick when the race result is known')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['race_time'],
            },
        ),
    ]
