# Generated by Django 6.0.1 on 2026-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='cons',
            field=models.TextField(blank=True, help_text="Add one con per line (e.g. 'Steps up in class', 'Unproven at distance')."),
        ),
        migrations.AddField(
            model_name='tip',
            name='pros',
            field=models.TextField(blank=True, help_text="Add one pro per line (e.g. 'Trainer in form', 'Good ground record')."),
        ),
    ]
