# Generated by Django 6.0.1 on 2026-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_cons_tip_pros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='confidence',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3, help_text='1–5 star confidence rating'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit or loss in points', max_digits=6),
        ),
    ]
