# Generated by Django 6.0.1 on 2026-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_tip_confidence_alter_tip_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='racecourse',
            field=models.CharField(choices=[('Aintree', 'Aintree'), ('Ascot', 'Ascot'), ('Ayr', 'Ayr'), ('Bangor-on-Dee', 'Bangor-on-Dee'), ('Bath', 'Bath'), ('Beverley', 'Beverley'), ('Brighton', 'Brighton'), ('Carlisle', 'Carlisle'), ('Cartmel', 'Cartmel'), ('Catterick', 'Catterick'), ('Chelmsford City', 'Chelmsford City'), ('Cheltenham', 'Cheltenham'), ('Chepstow', 'Chepstow'), ('Chester', 'Chester'), ('Doncaster', 'Doncaster'), ('Epsom', 'Epsom'), ('Exeter', 'Exeter'), ('Fakenham', 'Fakenham'), ('Fontwell', 'Fontwell'), ('Goodwood', 'Goodwood'), ('Hamilton Park', 'Hamilton Park'), ('Haydock', 'Haydock'), ('Hereford', 'Hereford'), ('Hexham', 'Hexham'), ('Huntingdon', 'Huntingdon'), ('Kelso', 'Kelso'), ('Kempton', 'Kempton'), ('Leicester', 'Leicester'), ('Lingfield', 'Lingfield'), ('Ludlow', 'Ludlow'), ('Market Rasen', 'Market Rasen'), ('Musselburgh', 'Musselburgh'), ('Newbury', 'Newbury'), ('Newcastle', 'Newcastle'), ('Newmarket', 'Newmarket'), ('Newton Abbot', 'Newton Abbot'), ('Nottingham', 'Nottingham'), ('Perth', 'Perth'), ('Plumpton', 'Plumpton'), ('Redcar', 'Redcar'), ('Ripon', 'Ripon'), ('Salisbury', 'Salisbury'), ('Sandown', 'Sandown'), ('Sedgefield', 'Sedgefield'), ('Southwell', 'Southwell'), ('Stratford', 'Stratford'), ('Taunton', 'Taunton'), ('Thirsk', 'Thirsk'), ('Uttoxeter', 'Uttoxeter'), ('Warwick', 'Warwick'), ('Wetherby', 'Wetherby'), ('Wincanton', 'Wincanton'), ('Windsor', 'Windsor'), ('Wolverhampton', 'Wolverhampton'), ('Worcester', 'Worcester'), ('Yarmouth', 'Yarmouth'), ('York', 'York')], max_length=100),
        ),
    ]
