# Generated by Django 6.0.1 on 2026-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_tip_racecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='race_date',
            field=models.DateField(default='2026-02-14', help_text='Date of the race'),
            preserve_default=False,
        ),
    ]
