# Generated by Django 6.0.1 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_membership_expiry_date_alter_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
