# Generated by Django 6.0.1 on 2026-02-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membership_warning_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='stripe_subscription_id',
            new_name='paypal_subscription_id',
        ),
    ]
